# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Edge Test Runner

on:
  push:
    branches: [master]
    paths:
      - "edge/*"
  pull_request:
    branches: [master]
    paths:
      - "edge/*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test Runner
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: cd edge && npm install && npm run build
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Test
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: cd edge && npm install && npm test
